### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PovelitelKra** [EmpireMediaScience/A1111-Web-UI-Installer#64]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

There is an error with the installation of some files on startup
ERROR: Exception:
Traceback (most recent call last):
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\urllib3\response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 96, in read
    self._close()
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 76, in _close
    self.__callback(result)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 353, in cache_response
    self._cache_set(cache_url, request, response, body, expires_time)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 274, in _cache_set
    self.serializer.dumps(request, response, body),
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 70, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 883, in pack
    self._pack(obj)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 862, in _pack
    return self._pack_map_pairs(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 968, in _pack_map_pairs
    self._pack(v, nest_limit - 1)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 862, in _pack
    return self._pack_map_pairs(
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 967, in _pack_map_pairs
    self._pack(k, nest_limit - 1)
  File "D:\ART\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 815, in _pack
    return self._buffer.write(obj)
MemoryError

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: D:\ART\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "D:\ART\stable-diffusion-webui\launch.py", line 351, in <module>
    prepare_environment()
  File "D:\ART\stable-diffusion-webui\launch.py", line 253, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "D:\ART\stable-diffusion-webui\launch.py", line 81, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "D:\ART\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
Error code: 2
![image](https://user-images.githubusercontent.com/129002434/227803626-0815d7b5-0d55-46b7-9255-8b397c83d5e3.png)
![image](https://user-images.githubusercontent.com/129002434/227803730-28f3ce31-76ea-496f-a5a9-16023a03f236.png)

### Steps to reproduce the problem

1. launched the program
2. an error occurred while installing files

### What should have happened?

files should be installed and a tab in the browser should open

### Version of the Installer/Launcher where the problem happens

V1.7.0

**Comment by Mozoloa** [comment]
here's a link to my paypal for the 10000$ donation you swore you'd give me : [paypal.me/leomozoloa](paypal.me/leomozoloa), thanks a lot

Other than that it could be that you're out of space or ram, but it's unrelated to this launcher
