### ISSUE TITLE
[Bug]: RuntimeError: Couldn't install clip.

### ISSUE THREAD

**Issue by baigua** [EmpireMediaScience/A1111-Web-UI-Installer#66]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

RuntimeError: Couldn't install clip.
Command: "D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 --prefer-binary
Error code: 1

### Steps to reproduce the problem

Cancel
venv "D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing clip
Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\launch.py", line 355, in <module>
    prepare_environment()
  File "D:\StableDiffusion\stable-diffusion-webui\launch.py", line 266, in prepare_environment
    run_pip(f"install {clip_package}", "clip")
  File "D:\StableDiffusion\stable-diffusion-webui\launch.py", line 129, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "D:\StableDiffusion\stable-diffusion-webui\launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install clip.
Command: "D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Cloning https://github.com/openai/CLIP.git (to revision d50d76daa670286dd6cacf3bcd80b5e4823fc8e1) to c:\users\12125\appdata\local\temp\pip-req-build-7jakzf38

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\12125\AppData\Local\Temp\pip-req-build-7jakzf38'
  Running command git rev-parse -q --verify 'sha^d50d76daa670286dd6cacf3bcd80b5e4823fc8e1'
  Running command git fetch -q https://github.com/openai/CLIP.git d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Running command git checkout -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  fatal: unable to access 'https://github.com/openai/CLIP.git/': Recv failure: Connection was reset
  fatal: could not fetch abc8a347e095c11c31b6a42a117f21630fa52bda from promisor remote
  error: subprocess-exited-with-error

  git checkout -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git checkout -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

### What should have happened?

the installing program stop here

### Version of the Installer/Launcher where the problem happens

A1111-Web-UI-Installer

**Comment by Mozoloa** [comment]
here's a link to my paypal for the 10000$ donation you just swore you'd give me : [paypal.me/leomozoloa](paypal.me/leomozoloa), thanks a lot for your generous donation
