### ISSUE TITLE
Error starting WEBUI

### ISSUE THREAD

**Issue by BrunoHeidem6214** [EmpireMediaScience/A1111-Web-UI-Installer#70]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

Error when starting the WEBUI

### Steps to reproduce the problem

1. I open the launcher
2. Press the LAUNCH WEBUI button
3. Gives error

### What should have happened?

open stable diffusion

### Version of the Installer/Launcher where the problem happens

Launcher Version 1.7.0

### Additional information, context and logs

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading A111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Settings file found, loading
 →   Updating Settings File  ✓
 i   Launcher Version 1.7.0
 i   No Launcher launch options
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Checking requirements :
 i   Python 3.10.6150.1013 found in registry:  C:\Users\luisr\AppData\Local\Programs\Python\Python310\
 i   Clearing PATH of any mention of Python
 →   Adding python 3.10 to path  ✓
 i   Git found and already in PATH:  C:\Program Files\Git\cmd\git.exe
 i   Automatic1111 SD WebUI found:  C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui
 i   One or more checkpoint models were found
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Loading Complete, opening launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   No arguments set
 i   Low VRAM (medvram) updated to True
 →   Updating Settings File  ✓
 i   Arguments are now: --medvram
 i   Enable Xformers updated to True
 →   Updating Settings File  ✓
 i   Arguments are now: --medvram --xformers
 i   Auto-Update Extensions updated to True
 →   Updating Settings File  ✓
 i   Arguments are now: --medvram --xformers
 i   There is no extension in the extensions folder
 i   Arguments are now: --medvram --xformers
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
Creating venv in directory C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv using python "C:\Users\luisr\AppData\Local\Programs\Python\Python310\python.exe"
venv "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Collecting torch==1.13.1+cu117
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 134, in __call__
    resp = _http_get_download(self._session, link)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 117, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 48, in send
    cached_response = self.controller.cached_request(request)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 155, in cached_request
    resp = self.serializer.loads(request, cache_data, body_file)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 95, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data, body_file)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 186, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 123, in unpackb
    unpacker.feed(packed)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 381, in feed
    self._buffer.extend(view)
MemoryError

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 355, in <module>
    prepare_environment()
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 257, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 81, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "C:\Users\luisr\OneDrive\Documentos\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
Error code: 2
Pressione qualquer tecla para continuar. . .

**Comment by Mozoloa** [comment]
here's a link to my paypal for the 10000$ donation you swore you'd give me : [paypal.me/leomozoloa](paypal.me/leomozoloa), thanks a lot

Other than that it could be that you're out of space or ram, but it's unrelated to this launcher
