### ISSUE TITLE
[Bug]: they say upgrade "pip"

### ISSUE THREAD

**Issue by leudemm233** [EmpireMediaScience/A1111-Web-UI-Installer#76]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [ ] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

I 
![image](https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/assets/110396461/265a5b71-d43d-4755-92b7-cd976fbcfaa8)

### Steps to reproduce the problem

1. Go to A1111 Web UI Autoinstaller
2. Press A1111 WebUI (Pin to Taskbar)
3. Wait
4. Launch web ui
5. And wait
![image](https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/assets/110396461/f6e6135d-8cc6-41b7-9759-80f83a96d417)

### What should have happened?

i don't know

### Version of the Installer/Launcher where the problem happens

V1.7.0

### Additional information, context and logs

  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.1
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\operations\prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 134, in __call__
    resp = _http_get_download(self._session, link)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\download.py", line 117, in _http_get_download
    resp = session.get(target_url, headers=HEADERS, stream=True)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_internal\network\session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 48, in send
    cached_response = self.controller.cached_request(request)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\controller.py", line 155, in cached_request
    resp = self.serializer.loads(request, cache_data, body_file)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 95, in loads
    return getattr(self, "_loads_v{}".format(ver))(request, data, body_file)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\cachecontrol\serialize.py", line 186, in _loads_v4
    cached = msgpack.loads(data, raw=False)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 125, in unpackb
    ret = unpacker._unpack()
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 590, in _unpack
    ret[key] = self._unpack(EX_CONSTRUCT)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\msgpack\fallback.py", line 603, in _unpack
    return bytes(obj)
MemoryError

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 369, in <module>
    prepare_environment()
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 271, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 95, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "C:\Users\Essadauoi\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118
Error code: 2
Appuyez sur une touche pour continuer...

**Comment by Mozoloa** [comment]
Lmao you edited the post to uncheck the required checkboxes, how sneaky
Anyway good luck with that error

**Comment by lion676** [comment]
i have the same problem. can to resolve this?
